library(feather)
library(tidyverse)
library(tidytext)
library(topicmodels)
library(broom)
#source("02_translation.R")

# Description of this Rscipt
######################################################################################
# Purpose: Detect the word change before and after the social movement
# by using statistical learing appoach
 

# Readin Files: ./data/df.feather
# Output: plots:   1)   
#                  2) 
######################################################################################

df<-read_feather("data/df")

df1989<- df %>%
  filter(Datetime >= as.Date("1989-06-04") & Datetime <= as.Date("1990-06-04")) %>%
  separate (year_month, c("Year", "Month"), sep="-") %>%
  # since "term" will be interfered with the "term" generated by the models
  mutate (word = term)
  

data1989<-df1989 %>%
  count (Datetime, word) %>%
  ungroup() %>%
  group_by (Datetime) %>%
  mutate (day_total = sum(n),
          percent = n / day_total) %>%
  ungroup()



model1989<- data1989 %>%
  group_by(word) %>%
  filter(sum(n) > 50) %>%
  do(tidy(glm(cbind(n, day_total - n) ~ Datetime, .,
              family = "binomial"))) %>%
  ungroup() %>%
  filter (term == "Datetime") %>%
  arrange (desc(abs(estimate))) %>%
  filter (p.value <= 0.0005) 



# plot the word change before and after the end of the social movement:

model1989 %>%
  mutate(adjusted.p.value = p.adjust(p.value)) %>%
  ggplot(aes(estimate, adjusted.p.value)) +
  theme_bw() + 
  geom_point() +
  scale_y_log10() +
  xlab("Estimated change over time") +
  ylab("Adjusted p-value") +
  labs(title="p-value vs. estimated change of the words during June 1989 - June 1990 (p<0.0005)")

png("upload.png", width = 600, height =400)
ggsave("graph/1989model.png") 

model1989_top6 <- model1989 %>%
  top_n(6,abs(estimate)) %>%
  mutate (En = translateCnWords(word))

write_feather(model1989_top6, "data/model1989_top6")

model1989_top6 %>%
  inner_join (data1989, by = "word") %>%
  ggplot(aes(Datetime, percent)) +
  geom_point() +
  geom_smooth(method = 'loess') +
  facet_wrap(~ En) + 
  labs (title = "Word change during 1989-1990", y ="Frequency", x ="Date")

png("upload.png", width = 600, height =400)
ggsave("graph/1989_word_change.png")
######################################################################################

df1986<- df %>%
  filter(Datetime >= as.Date("1986-12-27") & Datetime <= as.Date("1987-12-27")) %>%
  separate (year_month, c("Year", "Month"), sep="-") %>%
  # since "term" will be interfered with the "term" generated by the models
  mutate (word = term)
  
data1986<-df1986 %>%
  count (Datetime, word) %>%
  ungroup() %>%
  group_by (Datetime) %>%
  mutate (day_total = sum(n),
          percent = n / day_total) %>%
  ungroup()



model1986<- data1986 %>%
  group_by(word) %>%
  filter(sum(n) > 50) %>%
  do(tidy(glm(cbind(n, day_total - n) ~ Datetime, .,
              family = "binomial"))) %>%
  ungroup() %>%
  filter (term == "Datetime") %>%
  arrange (desc(abs(estimate))) %>%
  filter (p.value <= 0.0005) 



# plot the word change before and after the end of the social movement:

model1986 %>%
  mutate(adjusted.p.value = p.adjust(p.value)) %>%
  ggplot(aes(estimate, adjusted.p.value)) +
  theme_bw() + 
  geom_point() +
  scale_y_log10() +
  xlab("Estimated change over time") +
  ylab("Adjusted p-value") +
  labs(title="p-value vs. estimated change of the words during December 1986 - December 1987 (p<0.0005)")

png("upload.png", width = 600, height =400)
ggsave("graph/1986model.png") 

model1986_top6 <- model1986 %>%
  top_n(6,abs(estimate)) %>%
  mutate (En = translateCnWords(word))

write_feather(model1986_top6, "data/model1986_top6")

model1986_top6 %>%
  inner_join (data1986, by = "word") %>%
  ggplot(aes(Datetime, percent)) +
  geom_point() +
  geom_smooth(method = 'loess') +
  facet_wrap(~ En) + 
  labs (title = "Word change during 1986-1987", y ="Frequency", x ="Date")

png("upload.png", width = 600, height =400)
ggsave("graph/1986_word_change.png") 











# conversion of the tidy data to  two DTM before crackdown and after crackdown
crk<-as.Date("1989-06-03")

dtm_before<- read_feather("data/df.feather") %>%
  filter (term !="　　") %>%
  filter(dates < crk) %>%
  cast_dtm(dates, term, count)  

dtm_after<- read_feather("data/df.feather") %>%
  filter (term !="　　") %>%
  filter(dates > crk) %>%
  cast_dtm(dates, term, count)
# do the LDA simulation for both of two periods with k=3 (arbitary)
before_lda <- LDA(dtm_before, k = 3, control = list(seed = 1234))
after_lda <- LDA(dtm_after, k = 3, control = list(seed = 1234))
# tidy the LDA model
before_lda_td<-tidy(before_lda )
after_lda_td<-tidy(after_lda )

######################################
# plot the top terms
######################################
# the topic model before the crackdown
top_terms_before <- before_lda_td %>%
  group_by(topic) %>%
  top_n(5, beta) %>%
  ungroup() %>%
  arrange(topic, -beta) %>%
  mutate(En_term=translateCnWords(term))

top_terms_before %>%
  mutate(En_term = reorder(En_term, beta)) %>%
  ggplot(aes(En_term, beta, fill = factor(topic))) +
  geom_bar(alpha = 0.8, width=0.5, stat = "identity", show.legend = FALSE) +
  facet_wrap(~ topic, scales="free")+
  coord_flip()+
  labs(title="Topic Model for People`s Daily before crackdown from May to June in 1989",
       x="term", y="beta")
png("upload.png", width = 800, height =400)
ggsave("graph/top_terms_before.png")

########################################
# the topic model after the crackdown
top_terms_after <- after_lda_td %>%
  group_by(topic) %>%
  top_n(5, beta) %>%
  ungroup() %>%
  arrange(topic, -beta) %>%
  mutate(En_term=translateCnWords(term))

top_terms_after %>%
  mutate(En_term = reorder(En_term, beta)) %>%
  ggplot(aes(En_term, beta, fill = factor(topic))) +
  geom_bar(alpha = 0.8, width=0.5, stat = "identity", show.legend = FALSE) +
  facet_wrap(~ topic, scales="free")+
  coord_flip()+
  labs(title="Topic Model for People`s Daily after crackdown from May to June in 1989",
       x="term", y="beta")
png("upload.png", width = 800, height =400)
ggsave("graph/top_terms_after.png")